ifdef SEPARATE_COMPILATION
SEPARATE_COMPILATION_LIB = libasio.a
SEPARATE_COMPILATION_CXXFLAGS = \
	-DASIO_SEPARATE_COMPILATION \
	-DASIO_ENABLE_CANCELIO
endif

CXXFLAGS = -g -Wall -Wextra -mthreads -I../include \
	$(OPTIM_CXXFLAGS) \
	$(BOOST_CXXFLAGS) \
	$(SEPARATE_COMPILATION_CXXFLAGS)
LDFLAGS = -g -mthreads $(OPTIM_LDFLAGS)
LIBS = $(SEPARATE_COMPILATION_LIB) -lws2_32 -lmswsock
DEFINES = -D_WIN32_WINNT=0x0501
